services:
  - type: web
    name: valentine-generator-public
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: MAX_EXPERIENCES_PER_IP
        value: 25

databases:
  - name: valentine-generator-db
    databaseName: valentine_experiences
    user: valentine_user